name: 'Build'

on:
  push:
    branches:
      - main
      - dev
      - "release*"
    tags:
      - '*'
  pull_request:

env:
  TARGETS: f7 f18
  DEFAULT_TARGET: f7
  FBT_TOOLCHAIN_PATH: /home/runner/work

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: 'Decontaminate previous build leftovers'
        run: |
          if [ -d .git ]; then
            git submodule status || git checkout "$(git rev-list --max-parents=0 HEAD | tail -n 1)"
          fi

      - name: 'Checkout code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Get commit details'
        id: names
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            TYPE="pull"
          elif [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            TYPE="tag"
          else
            TYPE="other"
          fi
          python3 scripts/get_env.py "--event_file=${{ github.event_path }}" "--type=$TYPE"
          echo random_hash=$(openssl rand -base64 40 | shasum -a 256 | awk '{print $1}') >> $GITHUB_OUTPUT
          echo "event_type=$TYPE" >> $GITHUB_OUTPUT

      - name: 'Make artifacts directory'
        run: |
          rm -rf artifacts
          mkdir artifacts

      - name: 'Bundle scripts'
        run: |
          tar czpf artifacts/flipper-z-any-scripts-${SUFFIX}.tgz scripts debug

      - name: 'Build the firmware'
        run: |
          set -e
          for TARGET in ${TARGETS}; do
            TARGET="$(echo "${TARGET}" | sed 's/f//')"; \
            ./fbt TARGET_HW=$TARGET copro_dist updater_package \
            ${{ startsWith(github.ref, 'refs/tags') && 'DEBUG=0 COMPACT=1' || '' }}
          done

      - name: 'Move upload files'
        run: |
          set -e
          for TARGET in ${TARGETS}; do
            mv dist/${TARGET}-*/* artifacts/
          done

      - name: "Check for uncommitted changes"
        run: |
          git diff --exit-code

      - name: 'Bundle resources'
        run: |
          tar czpf "artifacts/flipper-z-any-resources-${SUFFIX}.tgz" -C assets resources

      - name: 'Bundle core2 firmware'
        run: |
          cp build/core2_firmware.tgz "artifacts/flipper-z-any-core2_firmware-${SUFFIX}.tgz"

      - name: 'Updater artifact'
        uses: actions/upload-artifact@v3
        with:
          name: updater
          path: |
            artifacts/f7-*

      - name: 'Firmware artifact'
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: |
            artifacts

      # - name: 'Find Previous Comment'
      #   if: ${{ github.event.pull_request }}
      #   uses: peter-evans/find-comment@v1
      #   id: fc
      #   with:
      #     issue-number: ${{ github.event.pull_request.number }}
      #     comment-author: 'github-actions[bot]'
      #     body-includes: 'Compiled firmware for commit'

      # - name: Artifact info
      #   id: artifact-info
      #   uses: dawidd6/action-download-artifact@v2
      #   with:
      #     dry_run: true

      # - name: 'Create or update comment'
      #   if: ${{ github.event.pull_request}}
      #   uses: peter-evans/create-or-update-comment@v1
      #   with:
      #     comment-id: ${{ steps.fc.outputs.comment-id }}
      #     issue-number: ${{ github.event.pull_request.number }}
      #     body: |
      #       **Compiled firmware for commit `${{steps.names.outputs.commit_sha}}`:**
      #       - [📦 Update package](${{steps.artifact-info.outputs.artifacts[0].archive_download_url}})
      #     edit-mode: replace

  compact:
    if: ${{ !startsWith(github.ref, 'refs/tags') }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Decontaminate previous build leftovers'
        run: |
          if [ -d .git ]
          then
            git submodule status \
              || git checkout "$(git rev-list --max-parents=0 HEAD | tail -n 1)"
          fi

      - name: 'Checkout code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
          ref: ${{ github.event.pull_request.head.sha }}

      - name: 'Get commit details'
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            TYPE="pull"
          elif [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            TYPE="tag"
          else
            TYPE="other"
          fi
          python3 scripts/get_env.py "--event_file=${{ github.event_path }}" "--type=$TYPE"

      - name: 'Build the firmware'
        run: |
          set -e
          for TARGET in ${TARGETS}; do
            TARGET="$(echo "${TARGET}" | sed 's/f//')"; \
            ./fbt TARGET_HW=$TARGET DEBUG=0 COMPACT=1 updater_package 
          done
